### ISSUE TITLE
Make website responsive

### ISSUE THREAD

**Issue by SaptakS** [PyConPune/pune.pycon.org#2]
The website as of now is not responsive to various device width and resolutions.

**Comment by SaptakS** [comment]
I think this issue can be closed now...

**Comment by aditya-konarde** [comment]
In mobile view, having the maps in the Venue section one below other would look better. It is currently crammed into a single row, which won't look good on a mobile with a smaller screen.

**Comment by aditya-konarde** [comment]
Update: Responsive view is broken for devices with the tablet form factor (Tested on my iPad mini as well as google responsive view.)
P.S. @SaptakS  Have we already considered [Bootstrap](https://getbootstrap.com/) for making the site responsive? 

<div>
<img src="https://cloud.githubusercontent.com/assets/6318164/20379813/3fcd4608-acc4-11e6-9b77-efbcb9bb5868.PNG" width="40%">
<img src="https://cloud.githubusercontent.com/assets/6318164/20379815/43e52ff8-acc4-11e6-9f3d-29f42ab46f3c.PNG" width="40%">
</div>

**Comment by SaptakS** [comment]
@aditya-konarde I will check the view and correct it. But I don't think adding bootstrap just for the sake of making responsive makes sense. @sayanchowdhury what do you think?
