### ISSUE TITLE
Create a About Page

### ISSUE THREAD

**Issue by sayanchowdhury** [PyConPune/pune.pycon.org#24]
The About page will have all the details about the conference. @kushaldas will be providing a write-up

**Comment by kiran3807** [comment]
Hi,
I have created a "about" page. Currently it has the text that we had in the home-page in the about anchor. Should I wait for the write up from @kushaldas  before I send a PR ? . Also the CSS for it currently is same as the one we have in the registration page. Any specific changes for the text and font ?.

Thanks
