### ISSUE TITLE
Add Information on T-Shirt Size

### ISSUE THREAD

**Issue by sara-02** [PyConPune/pune.pycon.org#34]
To help participants make more informed choice, there should be some information regarding the t-shirt size. Different people have different perception of what is Large or Medium.

**Comment by sayanchowdhury** [comment]
@sohamd3 we can add a size chart in registration page?

**Comment by sohamd3** [comment]
@sayanchowdhury - Yes it can be added. Well, the best position would be, just above the drop down where a user selects the T-shirt size. Only issue is there is a little space constraint, so, give me some time to think over the visualization.

**Comment by sara-02** [comment]
@sohamd3 You can just add an external link to a image/chart or pdf instead of putting it on the on the page itself.
