### ISSUE TITLE
[Page] [About] Code of Conduct Page

### ISSUE THREAD

**Issue by sayanchowdhury** [PyConPune/pune.pycon.org#48]
We need to migrate this from last years Code of Conduct Page.

**Comment by anshulxyz** [comment]
hey, I'd like to work on this

**Comment by sayanchowdhury** [comment]
Feel free to work on it, check out the steps to setup the repo. Drop a note here/IRC/Telegram for any issues.

**Comment by anshulxyz** [comment]
@sayanchowdhury the CoC page is already there. 
![selection_003](https://user-images.githubusercontent.com/6121530/30773283-761bbbb6-a08b-11e7-826d-bf07722c2287.png)

**Comment by SaptakS** [comment]
@anshulc95 yes you are right. This has already been done. Closing.
