### ISSUE TITLE
On clicking an option in navbar, it doesn't scroll to correct location.

### ISSUE THREAD

**Issue by SaptakS** [PyConPune/pune.pycon.org#5]
For example, if we click on [sprints,](http://pune.pycon.org/#sprints) we should ideally scroll to the heading circle part.

**Comment by importerror** [comment]
Shall we add lazy scroll to this?

**Comment by SaptakS** [comment]
@sant0sh apart from lazy scroll, what I think first is needed is to scroll to the correct area... I think referencing to the headings of an area is a better option than the div for that area. That way it always scrolls to the heading portion. But the div may start below or above the headings sometimes depending on margin and whitespaces. What do you think?

**Comment by importerror** [comment]
When implementing lazy scroll, it will be redirected to the section. Il work on this. Minor margin issue is fine.
