### ISSUE TITLE
[Page] Volunteering

### ISSUE THREAD

**Issue by sayanchowdhury** [PyConPune/pune.pycon.org#59]
Volunteering tasks & slots.

**Comment by vbnlohani** [comment]
I would like to work on this.

**Comment by SaptakS** [comment]
@vbnlohani sure. Go ahead.

**Comment by vbnlohani** [comment]
Do we need to only publish the tasks and slots for them, or entries for those slots from interested volunteers are required to be accepted ?

**Comment by jatanmalde** [comment]
I would like to be apart of it

**Comment by vbnlohani** [comment]
Actually, currently, it is just a static page, and it has been mostly done.
