### ISSUE TITLE
[Page][Home] Speaker twitter links

### ISSUE THREAD

**Issue by SaptakS** [PyConPune/pune.pycon.org#68]
Add links for speaker's twitter profile and other social links.

**Comment by anshulxyz** [comment]
I want to work on this.

**Comment by SaptakS** [comment]
@anshulc95 go ahead. You can get the details here: https://pune.pycon.org/2018/#speakers First try to run the project in your local system

**Comment by anshulxyz** [comment]
@SaptakS there already are twitter and GitHub links of the speakers, on the hmepage. I am not clear about what's the issue here!

**Comment by SaptakS** [comment]
@anshulc95 The code that is live now is not the final version. You have to implement this in the development branch. While the code that is live now is the 2018 branch. The development branch is written in django. It's in beta phase right now. Soon to be live.

**Comment by anshulxyz** [comment]
okay @SaptakS got it, on it
