### ISSUE TITLE
[Page][Volunteers] Make separate `Volunteers` page

### ISSUE THREAD

**Issue by SaptakS** [PyConPune/pune.pycon.org#77]
- [ ] Separate `Be a Volunteer` page from the `Volunteers` page and make two different pages.
- [ ] Link them in the footer accordingly.

**Comment by aman-roy** [comment]
Can I work on this?

**Comment by SaptakS** [comment]
@aman-roy sure. Go ahead.

**Comment by aman-roy** [comment]
Please review pull request.
