### ISSUE TITLE
Send in the information to python events calendar 

### ISSUE THREAD

**Issue by kushaldas** [PyConPune/pune.pycon.org#9]
https://wiki.python.org/moin/PythonEventsCalendar

Submit the event to the calendar, expected attendees: 700

Remember to assign the ticket to yourself first. Keep it open till it goes live.

**Comment by sayanchowdhury** [comment]
@girish946 is working on this ticket.

**Comment by girish946** [comment]
@sayanchowdhury yes.

**Comment by girish946** [comment]
mail sent to events@python.org.
